#!/usr/bin/env bash

set -eufo pipefail

function is_elf (
	[ "$(od -A n -t x1 -N 4 "$1" | tr -d ' ')" = "7f454c46" ]
)

function export_elf (
	file="$1"
	new_file="/native/$(basename "$file")"
	[ ! -e "$new_file" ]
	cat < "$file" > "$new_file"
	if [ -x "$file" ]; then
		chmod +x "$new_file"
	fi
	patchelf --remove-rpath "$new_file"
	if interpreter="$(patchelf --print-interpreter "$new_file" 2> /dev/null)"; then
		new_interpreter="/native/$(basename "$interpreter")"
		[ -e "$new_interpreter" ] || export_elf "$interpreter"
		chmod 755 "$new_interpreter"
		patchelf --set-interpreter "$new_interpreter" "$new_file"
	fi
	patchelf --print-needed "$new_file" | while read lib; do
		lib_path="$(realpath "$(ldconfig -p | grep "^\s*$lib " | awk -F ' => ' '{ print $2 }' | head -n 1)")"
		new_lib="/native/$(basename "$lib_path")"
		[ -e "$new_lib" ] || export_elf "$lib_path"
		patchelf --replace-needed "$lib" "$new_lib" "$new_file"
	done

	echo "exported $file -> $new_file"
	ldd "$new_file" 2> /dev/null || true
)

function export {
	mkdir -p /native
	export_elf /usr/bin/tail
}

function import {
	cat < /native/tail > /usr/bin/tail
}

action="$1"
shift

"$action" "$@"
